name: Docker Image CI

on:
  push:
    branches: [ master, development, blue, green ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag swadeshness-project:$(date +%s)
